/**
 * NovaCart Store Inventory & Layout Catalog
 * High-fidelity realistic supermarket catalog with exact physical weight tolerances and allergen metadata
 */

import { Product, StoreAisle } from '../types';

export const STORE_AISLES: StoreAisle[] = [
  { id: 'aisle-1', name: 'Fresh Produce & Greens', category: 'Produce', number: 1, x: 50, y: 80, width: 140, height: 260, color: '#10b981' },
  { id: 'aisle-2', name: 'Artisan Bakery & Grains', category: 'Bakery', number: 2, x: 230, y: 80, width: 140, height: 260, color: '#f59e0b' },
  { id: 'aisle-3', name: 'Dairy & Cold Beverages', category: 'Dairy & Refrigerated', number: 3, x: 410, y: 80, width: 140, height: 260, color: '#06b6d4' },
  { id: 'aisle-4', name: 'Organic Meat & Sustainable Seafood', category: 'Meat & Seafood', number: 4, x: 590, y: 80, width: 140, height: 260, color: '#f43f5e' },
  { id: 'aisle-5', name: 'Gourmet Pantry, Oils & Pasta', category: 'Pantry & Grains', number: 5, x: 50, y: 390, width: 140, height: 260, color: '#8b5cf6' },
  { id: 'aisle-6', name: 'Artisan Snacks & Healthy Bites', category: 'Snacks', number: 6, x: 230, y: 390, width: 140, height: 260, color: '#ec4899' },
  { id: 'aisle-7', name: 'Cold Pressed Juices & Tonics', category: 'Beverages', number: 7, x: 410, y: 390, width: 140, height: 260, color: '#3b82f6' },
  { id: 'aisle-8', name: 'Eco Household & Personal Care', category: 'Household', number: 8, x: 590, y: 390, width: 140, height: 260, color: '#14b8a6' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'PROD-ORG-APP-01',
    barcode: '890100100101',
    name: 'Organic Honeycrisp Apples (Bag)',
    category: 'Produce',
    price: 5.49,
    weightGrams: 1360, // 3 lb bag = ~1360g
    weightToleranceGrams: 40,
    aisle: 'Aisle 1',
    shelf: 'Shelf 1-B',
    coordinates: { x: 120, y: 140 },
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free', 'Organic', 'Non-GMO'],
    calories: 95,
    carbonScoreKg: 0.35,
    stockLevel: 48,
    description: 'Crisp, sweet, hand-picked Washington State organic Honeycrisp apples.'
  },
  {
    id: 'prod-002',
    sku: 'PROD-ORG-AVO-02',
    barcode: '890100100102',
    name: 'Organic Hass Avocados (4-Pack)',
    category: 'Produce',
    price: 4.99,
    weightGrams: 680,
    weightToleranceGrams: 30,
    aisle: 'Aisle 1',
    shelf: 'Shelf 1-A',
    coordinates: { x: 80, y: 110 },
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Keto', 'Gluten-Free', 'Organic'],
    calories: 240,
    carbonScoreKg: 0.55,
    stockLevel: 62,
    description: 'Creamy Hass avocados rich in healthy monounsaturated fats.'
  },
  {
    id: 'prod-003',
    sku: 'PROD-ORG-SPN-03',
    barcode: '890100100103',
    name: 'Baby Spinach Clamshell (16oz)',
    category: 'Produce',
    price: 3.99,
    weightGrams: 454,
    weightToleranceGrams: 20,
    aisle: 'Aisle 1',
    shelf: 'Shelf 1-C',
    coordinates: { x: 150, y: 220 },
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Keto', 'Gluten-Free', 'Organic'],
    calories: 23,
    carbonScoreKg: 0.20,
    stockLevel: 35,
    description: 'Triple-washed organic tender baby spinach leaves.'
  },
  {
    id: 'prod-004',
    sku: 'BAK-SRD-BRD-01',
    barcode: '890100200201',
    name: 'San Francisco Sourdough Boule',
    category: 'Bakery',
    price: 4.79,
    weightGrams: 650,
    weightToleranceGrams: 25,
    aisle: 'Aisle 2',
    shelf: 'Shelf 2-A',
    coordinates: { x: 260, y: 120 },
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=400&q=80',
    allergens: ['gluten'],
    dietaryTags: ['Vegetarian', 'Non-GMO'],
    calories: 160,
    carbonScoreKg: 0.42,
    stockLevel: 22,
    description: 'Naturally fermented rustic sourdough with crisp golden crust.'
  },
  {
    id: 'prod-005',
    sku: 'BAK-GF-OAT-02',
    barcode: '890100200202',
    name: 'Gluten-Free Seeded Oat Bread',
    category: 'Bakery',
    price: 6.29,
    weightGrams: 510,
    weightToleranceGrams: 15,
    aisle: 'Aisle 2',
    shelf: 'Shelf 2-B',
    coordinates: { x: 300, y: 200 },
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free', 'Non-GMO'],
    calories: 140,
    carbonScoreKg: 0.38,
    stockLevel: 19,
    description: 'Certified gluten-free loaf with flax, chia, and pumpkin seeds.'
  },
  {
    id: 'prod-006',
    sku: 'DAI-PAS-MLK-01',
    barcode: '890100300301',
    name: 'Grass-Fed Whole Milk (Half Gallon)',
    category: 'Dairy & Refrigerated',
    price: 4.29,
    weightGrams: 1940, // Half gallon liquid milk weight ~ 1.94kg
    weightToleranceGrams: 35,
    aisle: 'Aisle 3',
    shelf: 'Shelf 3-A',
    coordinates: { x: 440, y: 130 },
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    allergens: ['dairy'],
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Organic'],
    calories: 150,
    carbonScoreKg: 1.85,
    stockLevel: 50,
    description: '100% pasture-raised whole milk from local family dairy farms.'
  },
  {
    id: 'prod-007',
    sku: 'DAI-OAT-MLK-02',
    barcode: '890100300302',
    name: 'Barista Oat Milk (32 fl oz)',
    category: 'Dairy & Refrigerated',
    price: 4.89,
    weightGrams: 980,
    weightToleranceGrams: 20,
    aisle: 'Aisle 3',
    shelf: 'Shelf 3-B',
    coordinates: { x: 480, y: 190 },
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free', 'Non-GMO'],
    calories: 120,
    carbonScoreKg: 0.60,
    stockLevel: 41,
    description: 'Silky smooth barista oat milk that foams beautifully.'
  },
  {
    id: 'prod-008',
    sku: 'DAI-GRK-YOG-03',
    barcode: '890100300303',
    name: 'Authentic Plain Greek Yogurt (32oz)',
    category: 'Dairy & Refrigerated',
    price: 5.79,
    weightGrams: 907,
    weightToleranceGrams: 20,
    aisle: 'Aisle 3',
    shelf: 'Shelf 3-C',
    coordinates: { x: 460, y: 260 },
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&q=80',
    allergens: ['dairy'],
    dietaryTags: ['Vegetarian', 'Keto', 'Gluten-Free'],
    calories: 130,
    carbonScoreKg: 1.10,
    stockLevel: 28,
    description: 'Traditional strained whole milk Greek yogurt with 18g protein per serving.'
  },
  {
    id: 'prod-009',
    sku: 'MEA-WLD-SLM-01',
    barcode: '890100400401',
    name: 'Wild Alaskan Sockeye Salmon Fillet',
    category: 'Meat & Seafood',
    price: 12.99,
    weightGrams: 454, // 1 lb fillet
    weightToleranceGrams: 20,
    aisle: 'Aisle 4',
    shelf: 'Shelf 4-A',
    coordinates: { x: 620, y: 130 },
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80',
    allergens: ['fish'],
    dietaryTags: ['Keto', 'Gluten-Free', 'Non-GMO'],
    calories: 220,
    carbonScoreKg: 2.10,
    stockLevel: 18,
    description: 'Sustainably wild-caught Alaskan sockeye salmon rich in Omega-3 fatty acids.'
  },
  {
    id: 'prod-010',
    sku: 'MEA-ORG-CHK-02',
    barcode: '890100400402',
    name: 'Organic Boneless Chicken Breast',
    category: 'Meat & Seafood',
    price: 8.99,
    weightGrams: 680, // ~1.5 lb pack
    weightToleranceGrams: 30,
    aisle: 'Aisle 4',
    shelf: 'Shelf 4-B',
    coordinates: { x: 660, y: 210 },
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Keto', 'Gluten-Free', 'Organic'],
    calories: 165,
    carbonScoreKg: 3.40,
    stockLevel: 25,
    description: 'Free-range, antibiotic-free organic chicken breasts.'
  },
  {
    id: 'prod-011',
    sku: 'PAN-EVO-OIL-01',
    barcode: '890100500501',
    name: 'Extra Virgin Olive Oil Single-Estate (500ml)',
    category: 'Pantry & Grains',
    price: 11.49,
    weightGrams: 750, // glass bottle + oil
    weightToleranceGrams: 25,
    aisle: 'Aisle 5',
    shelf: 'Shelf 5-A',
    coordinates: { x: 80, y: 440 },
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Keto', 'Gluten-Free', 'Non-GMO'],
    calories: 120,
    carbonScoreKg: 0.90,
    stockLevel: 32,
    description: 'Cold-pressed extra virgin olive oil from Sicilian olive groves.'
  },
  {
    id: 'prod-012',
    sku: 'PAN-ORG-QUI-02',
    barcode: '890100500502',
    name: 'Organic Tricolor Quinoa (16oz)',
    category: 'Pantry & Grains',
    price: 4.49,
    weightGrams: 454,
    weightToleranceGrams: 10,
    aisle: 'Aisle 5',
    shelf: 'Shelf 5-B',
    coordinates: { x: 120, y: 520 },
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free', 'Organic'],
    calories: 170,
    carbonScoreKg: 0.40,
    stockLevel: 45,
    description: 'Nutrient-dense ancient grains with a nutty flavor and complete protein profile.'
  },
  {
    id: 'prod-013',
    sku: 'SNK-ALM-RST-01',
    barcode: '890100600601',
    name: 'Sea Salt Roasted Almonds (12oz)',
    category: 'Snacks',
    price: 6.99,
    weightGrams: 340,
    weightToleranceGrams: 10,
    aisle: 'Aisle 6',
    shelf: 'Shelf 6-A',
    coordinates: { x: 260, y: 440 },
    image: 'https://images.unsplash.com/photo-1508061252445-5350f37d6e42?auto=format&fit=crop&w=400&q=80',
    allergens: ['tree_nuts'],
    dietaryTags: ['Vegan', 'Keto', 'Gluten-Free', 'Non-GMO'],
    calories: 170,
    carbonScoreKg: 0.85,
    stockLevel: 38,
    description: 'Slow-roasted California almonds lightly dusted with Pacific sea salt.'
  },
  {
    id: 'prod-014',
    sku: 'SNK-PNT-BUT-02',
    barcode: '890100600602',
    name: 'Organic Creamy Peanut Butter (16oz)',
    category: 'Snacks',
    price: 4.99,
    weightGrams: 620, // glass jar + peanut butter
    weightToleranceGrams: 20,
    aisle: 'Aisle 6',
    shelf: 'Shelf 6-B',
    coordinates: { x: 300, y: 520 },
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=400&q=80',
    allergens: ['peanuts'],
    dietaryTags: ['Vegan', 'Keto', 'Gluten-Free', 'Organic'],
    calories: 190,
    carbonScoreKg: 0.75,
    stockLevel: 29,
    description: '1-ingredient organic Valencia roasted peanut butter with zero palm oil.'
  },
  {
    id: 'prod-015',
    sku: 'BEV-KMB-GNG-01',
    barcode: '890100700701',
    name: 'Live Probiotic Ginger Kombucha (16oz)',
    category: 'Beverages',
    price: 3.79,
    weightGrams: 640, // glass bottle + kombucha
    weightToleranceGrams: 15,
    aisle: 'Aisle 7',
    shelf: 'Shelf 7-A',
    coordinates: { x: 440, y: 440 },
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free', 'Organic'],
    calories: 30,
    carbonScoreKg: 0.30,
    stockLevel: 56,
    description: 'Raw, fermented sparkling probiotic tea with fresh cold-pressed ginger root.'
  },
  {
    id: 'prod-016',
    sku: 'HOU-ECO-DSH-01',
    barcode: '890100800801',
    name: 'Plant-Based Dish Soap Citrus (24oz)',
    category: 'Household',
    price: 4.29,
    weightGrams: 750,
    weightToleranceGrams: 25,
    aisle: 'Aisle 8',
    shelf: 'Shelf 8-A',
    coordinates: { x: 620, y: 440 },
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=400&q=80',
    allergens: [],
    dietaryTags: ['Vegan', 'Non-GMO'],
    calories: 0,
    carbonScoreKg: 0.45,
    stockLevel: 30,
    description: 'Biodegradable, dye-free dish soap powered by coconut surfactants.'
  }
];

export const FLEET_SIMULATED_CARTS = [
  {
    cartId: 'CART-101',
    assignedShopper: 'Alex Chen (Current Session)',
    battery: 94,
    currentAisle: 'Aisle 1',
    itemCount: 3,
    totalValue: 14.47,
    riskScore: 4,
    status: 'active' as const,
    lastPingTime: Date.now() - 2000,
    weightVarianceGrams: 2,
    activeAnomalies: []
  },
  {
    cartId: 'CART-102',
    assignedShopper: 'Marcus Vance',
    battery: 88,
    currentAisle: 'Aisle 4',
    itemCount: 8,
    totalValue: 74.20,
    riskScore: 82,
    status: 'flagged' as const,
    lastPingTime: Date.now() - 4000,
    weightVarianceGrams: 650, // Major weight mismatch: 650g unaccounted!
    activeAnomalies: ['Unscanned weight detected on load cell (+650g)', 'Walkout proximity zone warning']
  },
  {
    cartId: 'CART-103',
    assignedShopper: 'Elena Rostova',
    battery: 76,
    currentAisle: 'Aisle 2',
    itemCount: 4,
    totalValue: 21.80,
    riskScore: 12,
    status: 'active' as const,
    lastPingTime: Date.now() - 7000,
    weightVarianceGrams: 8,
    activeAnomalies: []
  },
  {
    cartId: 'CART-104',
    assignedShopper: 'Guest Shopper #419',
    battery: 62,
    currentAisle: 'Aisle 5',
    itemCount: 1,
    totalValue: 11.49,
    riskScore: 95,
    status: 'locked' as const,
    lastPingTime: Date.now() - 1000,
    weightVarianceGrams: 820,
    activeAnomalies: ['Barcode swap attempt: Premium EVOO scanned as 49c Onion', 'Emergency remote wheel lock engaged']
  }
];
